#ifndef __UEFI__EFI_H__
#define __UEFI__EFI_H__

#include "Typedef.h"

#if 0
// PE32+ Subsystem type for EFI images
#define EFI_IMAGE_SUBSYSTEM_EFI_APPLICATION 10
#define EFI_IMAGE_SUBSYSTEM_EFI_BOOT_SERVICE_DRIVER 11
#define EFI_IMAGE_SUBSYSTEM_EFI_RUNTIME_DRIVER 12
// PE32+ Machine type for EFI images
#define EFI_IMAGE_MACHINE_IA32 0x014c
#define EFI_IMAGE_MACHINE_IA64 0x0200
#define EFI_IMAGE_MACHINE_EBC 0x0EBC
#define EFI_IMAGE_MACHINE_x64 0x8664
#define EFI_IMAGE_MACHINE_ARMTHUMB_MIXED 0x01C2
#define EFI_IMAGE_MACHINE_AARCH64 0xAA64
#define EFI_IMAGE_MACHINE_RISCV32 0x5032
#define EFI_IMAGE_MACHINE_RISCV64 0x5064
#define EFI_IMAGE_MACHINE_RISCV128 0x5128
#endif

constexpr EFI_STATUS EFI_SUCCESS = 0;

class EFI_GUID {
public:
	BOOLEAN	operator ==(const EFI_GUID rcGUID) const {
		return rcGUID.Data1 == Data1 && rcGUID.Data2 == Data2 && rcGUID.Data3 == Data3 /* && rcGUID.Data4 == Data4 */;
	};

	UINT32	Data1;
	UINT16	Data2;
	UINT16	Data3;
	UINT8	Data4[8];
};

extern const EFI_GUID EFI_ACPI_20_TABLE_GUID;

// ======== UEFI Protocols ========
#if 0
EFI_LOADED_IMAGE_PROTOCOL
EFI_LOADED_IMAGE_DEVICE_PATH_PROTOCOL
EFI_DEVICE_PATH_PROTOCOL
EFI_DRIVER_BINDING_PROTOCOL
EFI_DRIVER_FAMILY_OVERRIDE_PROTOCOL
EFI_PLATFORM_DRIVER_OVERRIDE_PROTOCOL
EFI_BUS_SPECIFIC_DRIVER_OVERRIDE_PROTOCOL
EFI_DRIVER_DIAGNOSTICS2_PROTOCOL
EFI_COMPONENT_NAME2_PROTOCOL
//EFI_SIMPLE_TEXT_INPUT_PROTOCOL
//EFI_SIMPLE_TEXT_OUTPUT_PROTOCOL
//EFI_SIMPLE_POINTER_PROTOCOL
EFI_SERIAL_IO_PROTOCOL
EFI_LOAD_FILE_PROTOCOL
EFI_LOAD_FILE2_PROTOCOL
EFI_SIMPLE_FILE_SYSTEM_PROTOCOL
EFI_FILE_PROTOCOL
EFI_DISK_IO_PROTOCOL
EFI_BLOCK_IO_PROTOCOL
EFI_BLOCK_IO2_PROTOCOL
EFI_UNICODE_COLLATION_PROTOCOL
EFI_PCI_ROOT_BRIDGE_IO_PROTOCOL
EFI_PCI_IO_PROTOCOL
EFI_USB_IO_PROTOCOL
EFI_SIMPLE_NETWORK_PROTOCOL
EFI_PXE_BASE_CODE_PROTOCOL
EFI_BIS_PROTOCOL
EFI_DEBUG_SUPPORT_PROTOCOL
EFI_DEBUGPORT_PROTOCOL
EFI_DECOMPRESS_PROTOCOL
EFI_EBC_PROTOCOL
EFI_GRAPHICS_OUTPUT_PROTOCOL
EFI_NVM_EXPRESS_PASS_THRU_PROTOCOL
EFI_EXT_SCSI_PASS_THRU_PROTOCOL
EFI_USB2_HC_PROTOCOL
EFI_AUTHENTICATION_INFO_PROTOCOL
EFI_DEVICE_PATH_UTILITIES_PROTOCOL
EFI_DEVICE_PATH_TO_TEXT_PROTOCOL
EFI_DEVICE_PATH_FROM_TEXT_PROTOCOL
EFI_EDID_DISCOVERED_PROTOCOL
EFI_EDID_ACTIVE_PROTOCOL
EFI_EDID_OVERRIDE_PROTOCOL
EFI_ISCSI_INITIATOR_NAME_PROTOCOL
EFI_TAPE_IO_PROTOCOL
EFI_MANAGED_NETWORK_PROTOCOL
EFI_ARP_SERVICE_BINDING_PROTOCOL
EFI_DHCP4_SERVICE_BINDING_PROTOCOL
EFI_DHCP4_PROTOCOL
EFI_TCP4_SERVICE_BINDING_PROTOCOL
EFI_TCP4_PROTOCOL
EFI_IP4_SERVICE_BINDING_PROTOCOL
EFI_IP4_PROTOCOL
EFI_IP4_CONFIG_PROTOCOL
EFI_IP4_CONFIG2_PROTOCOL
EFI_UDP4_SERVICE_BINDING_PROTOCOL
EFI_UDP4_PROTOCOL
EFI_MTFTP4_SERVICE_BINDING_PROTOCOL
EFI_MTFTP4_PROTOCOL
EFI_HASH_PROTOCOL
EFI_HASH_SERVICE_BINDING_PROTOCOL
EFI_SD_MMC_PASS_THRU_PROTOCOL
#endif

struct EFI_TABLE_HEADER {
	UINT64	Signature;
	UINT32	Revision;
	UINT32	HeaderSize;
	UINT32	CRC32;
	UINT32	Reserved;
};

constexpr auto EFI_SYSTEM_TABLE_SIGNATURE = 0x5453595320494249;
constexpr auto EFI_2_80_SYSTEM_TABLE_REVISION = ((2 << 16) | (80));
constexpr auto EFI_2_70_SYSTEM_TABLE_REVISION = ((2 << 16) | (70));
constexpr auto EFI_2_60_SYSTEM_TABLE_REVISION = ((2 << 16) | (60));
constexpr auto EFI_2_50_SYSTEM_TABLE_REVISION = ((2 << 16) | (50));
constexpr auto EFI_2_40_SYSTEM_TABLE_REVISION = ((2 << 16) | (40));
constexpr auto EFI_2_31_SYSTEM_TABLE_REVISION = ((2 << 16) | (31));
constexpr auto EFI_2_30_SYSTEM_TABLE_REVISION = ((2 << 16) | (30));
constexpr auto EFI_2_20_SYSTEM_TABLE_REVISION = ((2 << 16) | (20));
constexpr auto EFI_2_10_SYSTEM_TABLE_REVISION = ((2 << 16) | (10));
constexpr auto EFI_2_00_SYSTEM_TABLE_REVISION = ((2 << 16) | (00));
constexpr auto EFI_1_10_SYSTEM_TABLE_REVISION = ((1 << 16) | (10));
constexpr auto EFI_1_02_SYSTEM_TABLE_REVISION = ((1 << 16) | (02));
constexpr auto EFI_SYSTEM_TABLE_REVISION = EFI_2_80_SYSTEM_TABLE_REVISION;
constexpr auto EFI_SPECIFICATION_VERSION = EFI_SYSTEM_TABLE_REVISION;

#include "EFI_BootServices.h"
#include "EFI_RuntimeServices.h"

struct EFI_CONFIGURATION_TABLE {
	EFI_GUID VendorGuid;
	VOID* VendorTable;
};

struct EFI_SYSTEM_TABLE {
	EFI_TABLE_HEADER Header;
	CHAR16* FirmwareVendor;
	UINT32 FirmwareRevision;
	EFI_HANDLE ConsoleInHandle;
	LPVOID ConIn;
	EFI_HANDLE ConsoleOutHandle;
	LPVOID ConOut;
	EFI_HANDLE StandardErrorHandle;
	LPVOID StdErr;
	EFI_RuntimeServices::Base* RuntimeServices;
	EFI_BootServices::Base* BootServices;
	UINTN NumberOfTableEntries;
	EFI_CONFIGURATION_TABLE* ConfigurationTable;
};

struct EFI_TIME {
	UINT16 Year; // 1900 ? 9999
	UINT8 Month; // 1 ? 12
	UINT8 Day; // 1 ? 31
	UINT8 Hour; // 0 ? 23
	UINT8 Minute; // 0 ? 59
	UINT8 Second; // 0 ? 59
	UINT8 Pad1;
	UINT32 Nanosecond; // 0 ? 999,999,999
	UINT16 TimeZone; // -1440 to 1440 or 2047
	UINT8 Daylight;
	UINT8 Pad2;
};

struct EFI_FILE_INFO {
	UINT64 Size;
	UINT64 FileSize;
	UINT64 PhysicalSize;
	EFI_TIME CreateTime;
	EFI_TIME LastAccessTime;
	EFI_TIME ModificationTime;
	UINT64 Attribute;
	CHAR16 FileName[100];
};

#endif // __UEFI__EFI_H__
